import keyMirror from "keymirror";
export default keyMirror({
  GOT_STORE_DESC: null,
  GOT_STORE_NAME: null,
  GOT_AUTH_USER: null,
  GOT_PROFILE: null,
  OPEN_MOB_MODAL: null,
  CLOSE_MOB_MODAL: null,
  OPEN_AUTH_MODAL: null,
  CLOSE_AUTH_MODAL: null,
  LOGOUT: null,
  GOT_STORE_URL: null,
  GOT_TASK_URL: null,
  GOT_ALL_TASK: null,
  GOT_TASK_DETAILS: null,
  GOT_HEAD_FOOT: null,
  GOT_BANNER_OFFER: null,
  GOT_WALLET: null,
  GOT_SIMILAR: null,
  GOT_USER_ACTIVITY: null,
  GOT_PAYMENT_METHODS: null,
  GOT_USER_PAY_INFO: null,
  GOT_REDEMPTION_BALANCE: null,
  GOT_REDEMPTION_HISTORY: null,
  GOT_CB_RATES: null,
  GOT_CATEGORY_NAME: null,
  GOT_AFF_CLICKS_DATA: null,
  GOT_CASHBACK_CLAIMS_DATA: null,
  GOT_NEWS_DATA: null,
  GOT_TESTIMONIALS_DATA: null,
  GOT_STORE_TASK_DATA: null,
  // GOT_STORE_BY_CATEGORY: null
});
